/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _V_H_RPCGEN
#define _V_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	char plik[512];
	char nazwaPliku[30];
	int wielkoscPliku;
};
typedef struct data data;

struct datax {
	char nazwaPliku[30];
};
typedef struct datax datax;

struct datay {
	char pliki[512];
};
typedef struct datay datay;

#define F 0x30000004
#define Fver 1

#if defined(__STDC__) || defined(__cplusplus)
#define Supload 1
extern  int * supload_1(data *, CLIENT *);
extern  int * supload_1_svc(data *, struct svc_req *);
#define Sdownload 2
extern  data * sdownload_1(datax *, CLIENT *);
extern  data * sdownload_1_svc(datax *, struct svc_req *);
#define Sshow 3
extern  datay * sshow_1(datax *, CLIENT *);
extern  datay * sshow_1_svc(datax *, struct svc_req *);
#define Sdelete 4
extern  int * sdelete_1(datax *, CLIENT *);
extern  int * sdelete_1_svc(datax *, struct svc_req *);
extern int f_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Supload 1
extern  int * supload_1();
extern  int * supload_1_svc();
#define Sdownload 2
extern  data * sdownload_1();
extern  data * sdownload_1_svc();
#define Sshow 3
extern  datay * sshow_1();
extern  datay * sshow_1_svc();
#define Sdelete 4
extern  int * sdelete_1();
extern  int * sdelete_1_svc();
extern int f_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);
extern  bool_t xdr_datax (XDR *, datax*);
extern  bool_t xdr_datay (XDR *, datay*);

#else /* K&R C */
extern bool_t xdr_data ();
extern bool_t xdr_datax ();
extern bool_t xdr_datay ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_V_H_RPCGEN */
