/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "v.h"


void
f_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	data  supload_1_arg;
	data  *result_2;
	datax  sdownload_1_arg;
	datay  *result_3;
	datax  sshow_1_arg;
	int  *result_4;
	datax  sdelete_1_arg;
/* Zmienne dodatkowe */
	char menu = 1;
	int opcja = 0;
	int temp;

/* Zmienne dodatkowe */
#ifndef	DEBUG
	clnt = clnt_create (host, F, Fver, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG -------------------------------------*/
	printf("\nKlient FTP - RPC\n");
	while(menu){
	printf("Wybierz numer opcji i zatwierdz enterem:\n");
	printf("1. Pokaz pliki na FTP\n");
	printf("2. Wyslij plik na FTP\n");
	printf("3. Pobierz plik z FTP\n");
	printf("4. Usun plik z FTP\n");
	printf("5. Zakoncz program\n");

	if( !(temp = scanf("%i",&opcja) )){
	    opcja = 9; 		//Nie wykonanie zadnego case
	    char x[100];
	    scanf("%s",x);	//Wyczyszczenie bufora scanf
	    printf("Wprowadz poprawna opcje..\n");
	}//if



	switch(opcja){
	case 1:/*Pokaz pliki na FTP*/
	{
	    result_3 = sshow_1(&sshow_1_arg, clnt);
	    if (result_3 == (datay *) NULL) {clnt_perror (clnt, "call failed");}
	    printf("Opcja 1\n");
	    printf("Opcja niedostepna w tej wersji\n");
	    break;
	}//case 1




	case 2:/*Wyslij plik na FTP*/
	{
	    printf("Opcja 2 - Wyslij na FTP\n");
	    /* Zmienne */
	    char bufor[512];
	    char nazwaPliku[30];
	    int wielkoscPliku;

	    /* Zerowanie pamieci dla zmiennych - alokacja */
	    memset(bufor, '\0', sizeof(char)* 512);
	    memset(nazwaPliku, '\0', sizeof(char)* 30);
	    wielkoscPliku = 0;

	    /* Otwarcie pliku i odczyt danych do bufora */
	    printf("Podaj nazwe pliku wraz z rozszerzeniem:\n");
	    scanf("%s",nazwaPliku);
	    FILE *fplik = fopen(nazwaPliku, "rb");
	    if( !fplik )
	    {
		printf("Plik nie istnieje..\n");
		break;
	    }//if

	    /* Sprawdzenie dlugosci pliku */
	    fseek(fplik, 0, SEEK_END);
	    wielkoscPliku = ftell(fplik);
	    fseek(fplik, 0, SEEK_SET);
	    if(wielkoscPliku > 511 )
	    {
		printf("Bufor zbyt maly..\n");
		fclose(fplik);
		break;
	    }//if

	    /* Odczyt z pliku do bufora */
	    fread(bufor, wielkoscPliku, 1, fplik);
	    fclose(fplik);
	    
	    /* Zaladowanie danych do struktury procedury zdalnej */
	    strcpy(supload_1_arg.plik, bufor);
	    strcpy(supload_1_arg.nazwaPliku,nazwaPliku);
	    supload_1_arg.wielkoscPliku = wielkoscPliku;

	    /* Wywoalnie procedury zdalnej - wyslanie pliku na serwer */
	    result_1 = supload_1(&supload_1_arg, clnt);
	    if (result_1 == (int *) NULL) {clnt_perror (clnt, "call failed");}
	    printf("Result: %d OK\n\n\n",*result_1);
	    break;
	}//case 2




	case 3:/*Pobierz plik z FTP*/
	{	
	    /* Zmienne */
	    char bufor[512];
	    char nazwaPliku[30];
	    int wielkoscPliku;
	    memset(bufor, '\0', sizeof(char)* 512);
	    memset(nazwaPliku, '\0', sizeof(char)* 30);
	    wielkoscPliku = 0;

	    /* Pobranie nazwy pliku od uzytkownika */
	    printf("Podaj nazwe pliku na FTP do pobrania:\n");
	    scanf("%s",nazwaPliku);

	    /* Zapisanie nazwy do argumentu funkji zdalej i jej wywolanie */
	    strcpy(sdownload_1_arg.nazwaPliku, nazwaPliku);
	    result_2 = sdownload_1(&sdownload_1_arg, clnt);
	    if (result_2 == (data *) NULL) {clnt_perror (clnt, "call failed");}

	    /* Zapis odebranego pliku do pamieci */
	    strcpy(bufor, result_2->plik);
	    strcpy(nazwaPliku, result_2->nazwaPliku);
	    wielkoscPliku = result_2->wielkoscPliku;
printf("%s\n",result_2->nazwaPliku);
printf("%d\n",result_2->wielkoscPliku);
	    /* Utworzenie pliku lub nadpisanie istniejacego */
	    FILE *fplik = fopen(nazwaPliku, "wb");
	    fwrite(bufor,wielkoscPliku,1,fplik);
	    fclose(fplik);

	    printf("Plik odebrano pomyslnie..\n");
	    break;
	}//case 3





	case 4:/*Usun plik z FTP*/
	{
	    result_4 = sdelete_1(&sdelete_1_arg, clnt);
	    if (result_4 == (int *) NULL) {clnt_perror (clnt, "call failed");}
	    printf("Result..\n");
	    break;
	}//case 4







	case 5:/*Zakoncz program*/
	{
	    printf("Opcja 5\n");
	    menu = 0;
	    break;
	}//case 5
	default:
	    break;

	}//switch
	}//while
	
#ifndef	DEBUG /*---------------------------------------*/
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	f_1 (host);
exit (0);
}
