/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "v.h"

int * supload_1_svc(data *argp, struct svc_req *rqstp)
{
	static int  result;//Automatycznie wygenerowana zmienna
	char bufor[512];
	char nazwaPliku[30];
	int wielkoscPliku;
	memset(bufor, '\0', sizeof(char)* 512);//Zerowanie bufora
	memset(nazwaPliku, '\0', sizeof(char)* 30);
	
	//Odebranie danych do buforow
	strcpy(bufor,argp->plik);
	strcpy(nazwaPliku,argp->nazwaPliku);
	wielkoscPliku = argp->wielkoscPliku;

	//Utworzenie pliku lub nadpisanie istniejacego
	FILE *fplik = fopen(nazwaPliku,"wb"); //Otwarcie w trybie binarnym
	fwrite(bufor, wielkoscPliku, 1, fplik);
	fclose(fplik);

	result = 1; //Zwrocenie do klienta 1
	printf("Supload >> odebrano: %s\n", nazwaPliku);
	return &result;
}//supload

data * sdownload_1_svc(datax *argp, struct svc_req *rqstp)
{
	static data  result;
	char bufor[512];
	//char nazwaPliku1[30];
	int wielkoscPliku;
	memset(bufor, '\0', sizeof(char)* 512);
	//memset(nazwaPliku1, '\0', sizeof(char)* 30);
	wielkoscPliku = 0;
	

	//Wczytanie pliku do bufora
	FILE *fplik = fopen(argp->nazwaPliku, "rb");
	if( !fplik )
	{
	    result.wielkoscPliku = 0;
	    strcpy(result.nazwaPliku,"error");
	    strcpy(result.plik,bufor);
	    fclose(fplik);
	    printf("Plik nie istnieje..\n");
	    return &result;
	    
	}//if

	//Sprawdzenie dlugosci pliku
	fseek(fplik, 0, SEEK_END);
	wielkoscPliku = ftell(fplik);
	fseek(fplik, 0, SEEK_SET);
	if( wielkoscPliku > 511 )
	{
	    fclose(fplik);
	    result.wielkoscPliku = 0;
	    strcpy(result.nazwaPliku,"error");
	    strcpy(result.plik,bufor);
	    return &result;
	}//if

	//Zaladowanie pliku do bufora
	fread(bufor, wielkoscPliku, 1, fplik);
	fclose(fplik);

	//Zapis do struktury wynikowej
	result.wielkoscPliku = wielkoscPliku;
	strcpy(result.plik, bufor);
	strcpy(result.nazwaPliku, argp->nazwaPliku);
	printf("Sdownload >> wyslano: %s\n",result.nazwaPliku);
	//Wyslanie pliku do klienta
	return &result;
}

datay * sshow_1_svc(datax *argp, struct svc_req *rqstp)
{
	static datay  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int * sdelete_1_svc(datax *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
